config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/store', to: 'home#store', as: 'store'
  patch '/store', to: 'items#buy', as: 'buy'
  post 'create' => 'tasks#create', as: 'create'
  patch '/', to: 'home#change', as: 'change'
  patch 'delete', to: 'tasks#delete', as: 'delete'
  patch 'complete', to: 'tasks#complete', as: 'complete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :avatars
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.find(current_user.id)
    default = Avatar.where(name: "0", user_id: current_user.id)
    if default.count == 0
      Avatar.create(name: "0", user_id: current_user.id)
    end
    @task = Task.new()
    if @user.item_id != -1
      @item = Item.find(@user.item_id)
    end
    if @user.tpoints and @user.points >= @user.tpoints and @item and @user.level == (@item.cost / 100 - 1)
      @user.level += 1
      @user.tpoints = 0
      @user.save
      Avatar.create(name: @user.level, user_id: current_user.id)
    end
    @avatars = Avatar.where(user_id: current_user.id)
  end

  def store
    @items = Item.all
    @user = User.find(current_user.id)
  end

  def change
    @user = User.find(current_user.id)
    @user.pic = params[:id]
    @user.save
    redirect_to root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  @@trainingPoints = 30
  def buy
    item = Item.find(params[:id])
    if current_user.points < item.cost
      flash[:error] = "Not enough points!"
    else
      user = User.find(current_user.id)
      user.points -= item.cost
      user.item_id = params[:id]
      user.tpoints = user.points + @@trainingPoints
      user.save
      flash[:success] = "Bought item."
    end
    redirect_to store_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
		@task = Task.new()
	end

	def create
		task = Task.create(description: params["task"]["description"], value: params["task"]["value"], user_id: current_user.id)
		task.save
		redirect_to '/'
	end

	def complete
		task = Task.find(params[:id])
		@user = User.find(current_user.id)
		@user.points += task.value
		@user.save
		task.destroy
		redirect_to '/'
	end

	def delete
		task = Task.find(params[:id])
		task.destroy
		redirect_to '/'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
	<div class="container-fluid offset">
    <div class="row">
        <div style="margin-top:5%" class="col-md-6 centered">

    			<%= image_tag("#{@user.pic}pusheen.gif", :class => "avatar-img") %>
          <br><br>
					Avatars:
					<% @avatars.each do |a| %>
						<%= link_to(image_tag("#{a.name}pusheen.gif", :class => "button-img"), change_path(id: a.name), method: :patch) %>
					<% end %>
					<br><br>
    			Level: <%= @user.level %>
          <br>
					<% if @user.item_id != -1 %>
						Equipped: <%= @item.name %>
					<% else %>
						Equipped: None
					<% end %>
					<br>
					<% if @user.tpoints != 0 and @user.points <= @user.tpoints %>
						In training. You need <%= @user.tpoints - @user.points %> more points to level up.<br>
					<% end %>
          <br>
          <%= button_to "Visit Store", store_path, form: {style: "display:inline-block"}, :class => "btn btn-primary", :method => :get %>
        </div>

        <div class="col-md-6 task centered">
            <h2 style="margin-top: 5%">Tasks</h2>
            <p>
                <%= simple_form_for @task, :html => {:class => 'form-inline' }, :url => {:action => "create", :controller => "tasks"} do |f| %>

            		<%= f.input :description, label: false, placeholder: "add a new task"%>
            		<%= f.input :value, label: false, placeholder: "difficulty: 1-10" %>
            		<%= f.button :submit, class: "btn-primary"%>

            		<%end %>
            </p>
            <p>
            	<%if @user.tasks%>
            		<%@user.tasks.each do |task| %>

            		<br/>
            			<%= button_to "Done", complete_path(id: task), :method => :patch %><%= button_to "x", delete_path(id: task), :method => :patch %><%= task.description %> <%= task.value%>
            		<%end%>
            	<%end%>
            	</p>
        </div>
    </div>
</div>

app/views/home/store.html.erb
<h5 style="margin-left: 2em" class="offset">Use your points to buy armor for your character.</h5>
<br>
<div class="row">
  <% @items.each do |i| %>
    <div class="col-md-3 centered">
      <%= image_tag("#{i.name}.svg", :size => "100x100") %>
      <br>
      <%= i.name %>
      <br>
      <%= i.cost %> points
      <% if (@user.level + 1)*100 >= i.cost %>
        <%= button_to "Buy", buy_path(id: i.id), :class => "btn btn-primary", :method => :patch %>
      <% else %>
        <br>
        <button class="btn btn-primary disabled">Buy</button>
      <% end %>
      <br>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pawductivity</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar fixed-top navbar-dark bg-primary">
      <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="http://localhost:3000">Pawductivity</a>
          </div>
          <div class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
            <br>
            <% if user_signed_in? %>
              <p style="float:right">
                Points: <%= User.find(current_user.id).points %>
              </p>
            <% end %>
          </div>
        </div>
    </nav>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-dismissible error alert-<%= key == "error" ? "danger" : "success"%>">
        <%= value %>
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>